[ERROR		:	Mon, 26, Mar 2018 10:02:41]	Traceback (most recent call last):
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "BoardUI.py", line 800, in <module>
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "BoardUI.py", line 98, in __init__
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "BoardUI.py", line 520, in loadCheckHash
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\main.py", line 685, in round_trip_load
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\main.py", line 636, in load
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\constructor.py", line 102, in get_single_data
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 75, in get_single_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 96, in compose_document
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 132, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 132, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 132, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 132, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 132, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 130, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 163, in compose_sequence_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 132, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 194, in compose_mapping_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\composer.py", line 106, in compose_node
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\parser.py", line 144, in check_event
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\parser.py", line 572, in parse_block_mapping_value
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\scanner.py", line 1620, in check_token
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\scanner.py", line 1662, in _gather_comments
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  File "site-packages\ruamel\yaml\scanner.py", line 310, in fetch_more_tokens
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	ruamel.yaml.scanner
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	.
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	ScannerError
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	:
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	while scanning for the next token
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	found character '\t' that cannot start any token
[ERROR		:	Mon, 26, Mar 2018 10:02:41]	  in "C:\zcu102_scui\tests\ZCU102\SC.yaml", line 2134, column 20
